### ISSUE TITLE
Change 'Seed' to a more intuitive name

### ISSUE THREAD

**Issue by llSourcell** [TwilioDevEd/eta-notifications-node#10]
The Seed folder should be named something more intuitive like 'default_orders'

**Comment by nebtrx** [comment]
Hi @llSourcell, regarding this, I used the same approach as in https://github.com/TwilioDevEd/ivr-recording-node/tree/master/seed, which @kwhinnery suggested to me

**Comment by jarodreyes** [comment]
Seed is fine @nebtrx

**Comment by nebtrx** [comment]
Thanks @jarodreyes
