### ISSUE TITLE
Environment variable configuration feedback

### ISSUE THREAD

**Issue by kwhinnery** [TwilioDevEd/eta-notifications-node#2]
Add `.env` to `.gitignore` so that changes to it would not be accidentally checked in by the developer. Any file that could contain credentials should never be allowed to go into source control. 

The preferred solution is to have a `.env.example` file that can be copied (if desired) to `.env` if the developer wants to configure their environment with a file instead of environment variables.

**Comment by nebtrx** [comment]
ok..done! It's coming in the next push
