### ISSUE TITLE
README missing key steps

### ISSUE THREAD

**Issue by kwhinnery** [TwilioDevEd/eta-notifications-node#3]
- Do I need to source the `.env` file?
- Why do I need ngrok?
- Do I need to configure a Twilio number to receive incoming messages?

The README as constituted cannot be followed by  developer. Needs another thorough review.

**Comment by jarodreyes** [comment]
@kwhinnery you need ngrok because we use status_callback to update the status of the notification. You do not need to configure any twilio numbers.

**Comment by nebtrx** [comment]
Fixed!
